In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
X ,y=make_classification(n_samples=1000,n_features=5,random_state=123)

In [4]:
X

array([[ 0.87728113, -0.59642825,  0.44019839, -0.52108094,  0.31432298],
       [ 0.55856502, -0.41451292,  0.813623  , -0.54325372,  0.14734302],
       [-0.90289911,  0.38303337, -0.71157267, -0.86768895, -0.67394137],
       ...,
       [ 1.7713853 , -0.96445461,  0.99337636,  0.40674576,  0.99881985],
       [-1.19977749,  0.48167954,  1.47831033, -1.31903526, -0.93698258],
       [ 0.33976266, -0.29183452, -0.82476815, -0.57191024,  0.02935597]])

In [5]:
y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,

In [7]:
X_train , X_test , y_train , y_test=train_test_split(X , y , test_size = 0.3 , random_state = 45)

In [8]:
X_train

array([[-1.46503112,  0.96648113, -0.71488077,  0.69053358, -0.56975163],
       [-0.40179796,  0.44521869, -0.1646712 ,  1.28522165,  0.11726498],
       [-0.95865983,  0.67190559,  0.804181  ,  0.69199408, -0.31288484],
       ...,
       [-0.68915941,  0.65060357, -0.9730118 ,  1.51685249,  0.02951794],
       [-0.79857044,  0.58699409,  1.11162249,  0.74244828, -0.21919807],
       [ 1.15345007, -0.49955037, -0.80495708,  1.04626176,  0.84543026]])

In [9]:
X_train.shape

(700, 5)

In [10]:
X_test.shape

(300, 5)

In [11]:
model = LogisticRegression()

In [12]:
#you are training your model here
model.fit(X_train,y_train)

LogisticRegression()

In [13]:
model.score(X_train,y_train)

0.9457142857142857

In [14]:
#my model means my logistic regression is able to 94% data

In [15]:
y_pred=model.predict(X_test)

In [16]:
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [17]:
accuracy_score(y_test,y_pred)

0.9633333333333334

In [18]:
confusion_matrix(y_test,y_pred)

array([[154,   6],
       [  5, 135]], dtype=int64)

In [19]:
# overfitting mean
# train accuracy is very good
# and test accruacy is not

In [20]:
# let'say there is medical problem statement which we are solving
# 10,20,30,40

In [21]:
# underfitting means
# train accuracy and test accuracy both are not good